BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "safety-monitor"
BBFILE_PATTERN_safety-monitor = "^${LAYERDIR}/"
BBFILE_PRIORITY_safety-monitor = "10"

LAYERDEPENDS_safety-monitor = "core"
LAYERSERIES_COMPAT_safety-monitor = "kirkstone scarthgap"
